name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: YuriCat/github-contribution-pacman@main
        with:
          github-user: ${{ github.repository_owner }}
          output: dist/pacman.svg
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-pacman
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
